app/course/api/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('list-create/', views.CourseListCreate.as_view()),

]

app/course/urls.py
from django.urls import path, include

app_name = 'course'

urlpatterns = [
    path('v1/', include('app.course.v1.urls')),
    path('api/', include('app.course.api.urls')),

]

app/course/v1/urls.py
from django.urls import path
from .views import CourseView, CourseDetail, lesson_detail

urlpatterns = [
    path('course/', CourseView.as_view(), name='course'),
    path('detail/<int:pk>/', CourseDetail.as_view(), name='detail'),
    path('detail/<int:course_id>/lesson/<int:pk>/', lesson_detail, name='lesson_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import RedirectView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="EDU API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    # swagger
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('admin/', admin.site.urls),



#]
# urlpatterns += i18n_patterns(  # i18 ni urlpatternsga qoshsak barchasi tarjima qilinadi

    # local app
    path('', RedirectView.as_view(pattern_name='main:index')), #patern_name - bu v1/ ga birdaniga otvoradi kak indexga
    path('', include('app.main.urls', namespace='main')),
    path('account/', include('app.account.urls', namespace='account')),
    path('blog/', include('app.blog.urls', namespace='blog')),
    path('course/', include('app.course.urls', namespace='course'))

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/blog/models.py
from django.db import models
from django.db.models.signals import post_save
from app.main.models import Category, Tag
from django.conf import settings
from ckeditor.fields import RichTextField


class Post(models.Model):
    title = models.CharField(max_length=221)
    image = models.ImageField(upload_to='blog/')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    tags = models.ManyToManyField(Tag)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Body(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_body')
    body = RichTextField()
    is_script = models.BooleanField(default=False)


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    parent_comment = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='comments') # urldan oldik
    body = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    top_level_comment_id = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"comment of {self.author} ({self.id})"

    @property # property - bu htmlda chaqirvolish uchun yoziladi yani nuqta bn chaqirladi
    def get_related_comments(self):
        qs = Comment.objects.filter(top_level_comment_id=self.id).exclude(id=self.id)
        if qs:
            return qs
        return None


def comment_post_save(instance, sender, created, *args, **kwargs):
    if created:
        top_level_comment = instance
        while top_level_comment.parent_comment:
            top_level_comment = top_level_comment.parent_comment
        instance.top_level_comment_id = top_level_comment.id
        instance.save()


post_save.connect(comment_post_save, sender=Comment)

app/course/models.py
from django.db import models
from django.conf import settings
from app.main.models import Category, Tag
from ckeditor.fields import RichTextField


class Timestamp(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


def file_path_for_cover(instance, filename):
    return f"courses/{instance.id}/cover/{filename}"


class Course(Timestamp):
    DIFFICULTY = (
        (0, 'Beginner'),
        (1, 'Intermediate'),
        (2, 'Advanced'),
    )
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, limit_choices_to={'role': 0})
    title = models.CharField(max_length=221)
    cover = models.ImageField(upload_to=file_path_for_cover, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    difficulty = models.IntegerField(choices=DIFFICULTY, default=0)
    body = RichTextField()
    price = models.DecimalField(decimal_places=2, max_digits=4, null=True, blank=True)  # 65.99
    discount_price = models.DecimalField(decimal_places=2, max_digits=4, null=True, blank=True)
    is_free = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title


def file_path(instance, filename):
    return f"courses/{instance.lesson.course.title}/{instance.lesson.title}/{filename}"


class Lesson(Timestamp):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    title = models.CharField(max_length=221)
    body = RichTextField()
    view = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class LessonFiles(Timestamp):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)  #/course_name/lesson_name/ files
    file = models.FileField(upload_to=file_path)
    is_main = models.BooleanField(default=False)

    def __str__(self):
        return self.lesson.title


class SoldCourse(models.Model):
    profile = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, limit_choices_to={'role': 1})
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.profile.user.username} -> {self.course.title}"

app/course/api/views.py
from rest_framework import static, generics, permissions
from .serializer import CourseSerializer
from ..models import Course, SoldCourse, Lesson, LessonFiles
from rest_framework.pagination import PageNumberPagination


class CourseListCreate(generics.ListCreateAPIView):
    # https://127.0.0.1:8000/course/api/list-create/
    queryset = Course.objects.all()
    serializer_class = CourseSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    pagination_class = PageNumberPagination
    page_size = 10

app/course/v1/views.py
from django.db.models import Q
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView, DetailView
from ..models import Course, Lesson, LessonFiles
from app.main.models import Category, Tag


class CourseView(ListView):
    queryset = Course.objects.all()
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        ctx = super().get_context_data()
        ctx['categories'] = Category.objects.all()
        ctx['tags'] = Tag.objects.all()
        ctx['recent_courses'] = Course.objects.order_by("-id")[:3]
        return ctx


    def get_queryset(self):  # moshlashuvchan filterlar
        qs = super().get_queryset()
        q = self.request.GET.get('q')
        cat = self.request.GET.get('category')
        tag = self.request.GET.get('tag')
        q_conditions = Q()
        if q:
            q_conditions = Q(title__icontains=q)
        cat_conditions = Q()
        if cat:
            cat_conditions = Q(category__title__exact=cat)
        tag_conditions = Q()
        if tag:
            tag_conditions = Q(tags__title__exact=tag)
        qs = qs.filter(q_conditions, cat_conditions, tag_conditions)
        return qs


class CourseDetail(DetailView):
    queryset = Course.objects.all()

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['recent_courses'] = Course.objects.order_by('-id')[:3]
        ctx['categories'] = Category.objects.all()
        ctx['tags'] = Tag.objects.all()
        ctx['random_5_course'] = Course.objects.order_by('?')[:5]
        return ctx


def post_view(request, pk):
    obj = Lesson.objects.get(id=pk)
    obj.views += 1
    obj.save()
    return redirect(reverse('project:lesson_detail', kwargs={'pk': pk}))


def lesson_detail(request, course_id,  pk):
    lesson = Lesson.objects.get(id=pk)
    main_lessons = LessonFiles.objects.filter(lesson_id=pk, is_main=True).first() #true - boganda har doim bitta boladi
    random_5_course = Course.objects.order_by('?')[:5]
    ctx = {
        'lesson': lesson,
        'main_lesson': main_lessons,
        'random_5_courses': random_5_course,
    }
    return render(request, 'course/course_lesson.html', ctx)

templates/course/course_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="site-hero site-sm-hero overlay" data-stellar-background-ratio="0.5"
         style="background-image: url({% static 'images/big_image_2.jpg' %});">
    <div class="container">
        <div class="row align-items-center justify-content-center site-hero-sm-inner">
            <div class="col-md-7 text-center">
                <div class="mb-5 element-animate">
                    <h1 class="mb-2">{{ object.title }}</h1>
                    <p class="bcrumb"><a href="{% url 'main:index' %}">Home</a> <span
                            class="sep ion-android-arrow-dropright px-2"></span> <a href="{% url 'course:course' %}">Course</a>
                        <span
                                class="sep ion-android-arrow-dropright px-2"></span> <span class="current">{{ object.title }}</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="site-section bg-light element-animate">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-8 order-md-2 mb-5">
                <div class="row">
                    <div class="col-md-12">
                        <img style="width:300px" src="{{ object.cover.url }}" alt="" class="img-fluid">
                    </div>
                </div>
                <section class="episodes">
                    <div class="container">
                        <div class="row mb-5">
                            <div class="col-md-12 pt-5">
                                <h2>Description</h2>
                                <p>{{ object.body|safe }}</p>
                            </div>
                        </div>
                    </div>
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12 mb-2">
                                <h2>Lesson</h2>
                            </div>
                        </div>
                        {% for lesson in object.lesson_set.all %}
                                               <! # forloop - bu order by ga oxshab ishlidi, count - bu qadamini olib beradi
                                                    # divisibleby - bu 2 ga bolinadiagn chiqarsn !>
                            <div class="row {% if not forloop.counter|divisibleby:2 %} bg-light{% endif %} align-items-center p-4 episode">
                            <div class="col-md-10">
                                <p class="meta">Episode {{ forloop.counter }} </p>
                                <h2><a href="{% url 'course:lesson_detail' object.id lesson.id %}">{{ lesson.title }}</a></h2>
                                <p>{{ lesson.body|safe|slice:'100' }}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </section>
            </div>

            <div class="col-md-6 col-lg-4 order-md-1">
                <div class="block-29 mb-5">
                    <h2 class="heading">Course Details</h2>
                    <ul>
                        <li><span class="text-1">Lesson:</span> <span
                                class="text-2">{{ object.lesson_set.count }}</span></li>
                        <li><span class="text-1">Difficulty:</span> <span class="text-2">{{ object.get_difficulty_display }}</span>
                        </li>
                        <li><span class="text-1">Language:</span> <span class="text-2">English</span></li>
                        <li><span class="text-1">Price:</span>
                            {% if discount_price %}
                            <del class="mr-3">${{ course.price }}</del>
                            {% endif %}
                            {% if course.is_free %}
                            <span>Free</span>
                            {% else %}
                            <del class="mr-3">${{ course.price }}</del>
                            {% endif %}
                        </li>
                    </ul>
                </div>
                <div class="block-28 text-center mb-5">
                    <figure>
                        <img src="
                        {% if object.author.image %}
                            {{ object.author.image.url }}
                        {% else %}
                            {% static 'images/anonymous .png' %}
                        {% endif %}
                        " alt="" class="img-fluid">
                    </figure>
                    <h2 class="heading">{{ object.author.user.username }}</h2>
                    <h3 class="subheading">{{ object.author.bio }}</h3>
                    <p>
                        <a href="#" class="fa fa-twitter p-2"></a>
                        <a href="#" class="fa fa-facebook p-2"></a>
                        <a href="#" class="fa fa-linkedin p-2"></a>
                    </p>
                    <p>Hi I'm Mark Stewart, consectetur adipisicing elit. Quibusdam nulla beatae modi itaque nemo magni
                        molestiae explicabo sint dolorum cum! Nam iste eligendi autem voluptates illo veritatis veniam
                        laudantium enim!</p>
                </div>
                <div class="block-25 mb-5">
                    <div class="heading">Recent Courses</div>
                    <ul>
                        {% for course in recent_courses %}
                        <li>
                            <a href="{% url 'course:detail' course.id %}" class="d-flex">
                                <figure class="image mr-3">
                                    <img src="{{ course.cover.url }}" alt="" class="img-fluid">
                                </figure>
                                <div class="text">
                                    <h3 class="heading">{{ course.title }}</h3>
                                    <span class="meta">{% if course.discount_price %}
                                                         <del class="mr-3">${{ course.discount_price }}</del>
                                                        {% endif %}
                                                        {% if course.price %}
                                                             <span>${{ course.price }}</span>
                                                        {% else %}
                                                            <span>Free</span>
                                                        {% endif %}
                                    </span>
                                </div>
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="block-24 mb-5">
                    <h3 class="heading">Categories</h3>
                    <ul>
                        {% for category in categories %}
                        <li>
                            <a href="{% if request.GET %}{{ request.get_full_path }}&category={{ category.title }}{% else %}{{ request.get_full_path }}?category={{ category.title }}{% endif %}">
                                {{ category.title }} <span>{{ category.post_set.count }}</span></a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="block-26">
                    <h3 class="heading">Tags</h3>
                    <ul>
                        {% for tag in tags %}
                        <li>
                            <a href="{% url 'course:course' %}{% if request.GET %}{{ request.get_full_path }}&tag={{ tag.title }}{% else %}{{ request.get_full_path }}?tag={{ tag.title }}{% endif %}">
                                {{ tag.title }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="site-section bg-light">
    <div class="container">
        <div class="row justify-content-center mb-5 element-animate">
            <div class="col-md-7 text-left section-heading">
                <h2 class="text-primary heading">You May Also Like</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit qui neque sint eveniet tempore
                    sapiente.</p>
            </div>
        </div>
    </div>
    <div class="container-fluid block-11 element-animate">
        <div class="nonloop-block-11 owl-carousel">
            {% for course in random_5_course %}
            <div class="item">
                <div class="block-19">
                    <figure>
                        <img src="{{ course.cover.url }}" alt="Image" class="img-fluid">
                    </figure>
                    <div class="text">
                        <h2 class="heading"><a href="{% url 'course:detail' course.id }}">{{ course.title }}</a></h2>
                        <p class="mb-4">{{ course.body|safe|slice:'100' }}</p>
                        <div class="meta d-flex align-items-center">
                            <div class="number">
                                <span>{{ course.soldcourse_set.count}}/600</span>
                            </div>
                            <div class="price text-right">
                                {% if course.discount_price %}
                                <del class="mr-3">${{ course.discount_price }}</del>
                                {% endif %}
                                {% if course.price %}
                                <span>${{ course.price }}</span>
                                {% else %}
                                <span>Free</span>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

</div>

<div class="py-5 block-22">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6 mb-4 mb-md-0 pr-md-5">
                <h2 class="heading">Create cool websites</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi accusantium optio und.</p>
            </div>
            <div class="col-md-6">
                <form action="#" class="subscribe">
                    <div class="form-group">
                        <input type="email" class="form-control email" placeholder="Enter email">
                        <input type="submit" class="btn btn-primary submit" value="Subscribe">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/course/course_lesson.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="site-hero site-sm-hero overlay" data-stellar-background-ratio="0.5"
         style="background-image: url({{ lesson.course.cover.url }});">
    <div class="container">
        <div class="row align-items-center justify-content-center site-hero-sm-inner">
            <div class="col-md-7 text-center">
                <div class="mb-5 element-animate">
                    <h1 class="mb-2">{{ lesson.title }}</h1>
                    <p class="bcrumb"><a href="{% url 'main:index' %}">Home</a> <span
                            class="sep ion-android-arrow-dropright px-2"></span> <a href="{% url 'course:course' %}">Course</a> <span
                            class="sep ion-android-arrow-dropright px-2"></span> <span class="current">{{ lesson.course.title }}</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="site-section bg-light element-animate">
    <div class="container" style="background-color: #b22222;">
        <div class="row">
             <div class="col-md-12 pt-1">
                 <h2>Description</h2>
                 <p>{{ object.body|safe }}</p>
             </div>
            <div class="col-md-12 col-lg-12 order-md-2 mb-1">

                <div class="col-md-12 mb-2">
                    <video style="width: 100%" controls src="{{ main_lesson.file.url }}"></video>
                </div>
                <div class="show_comments mt-1">
                    <pre><h5><span class="fa fa-eye" style="color: #fff;"> {{ main_lesson.views }}</span></h5></pre>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="site-section bg-light">
    <div class="container">
        <div class="row justify-content-center mb-5 element-animate">
            <div class="col-md-7 text-left section-heading">
                <h2 class="text-primary heading">You May Also Like</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit qui neque sint eveniet tempore
                    sapiente.</p>
            </div>
        </div>
    </div>
    <div class="container-fluid block-11 element-animate">
        <div class="nonloop-block-11 owl-carousel">
            {% for random in random_5_courses %}
            <div class="item">
                <div class="block-19">
                    <figure>
                        <img src="{{ random.cover.url }}" alt="Image" class="img-fluid">
                    </figure>
                    <div class="text">
                        <h2 class="heading"><a href="{% url 'course:detail' random.id %}">{{ random.title }}</a></h2>
                        <p class="mb-4">{{ random.body|safe|slice:"200" }}</p>
                        <div class="meta d-flex align-items-center">
                            <div class="number">
                                <span>{{ random.soldcourse_set.count}}/600</span>
                            </div>
                            <div class="price text-right">
                                {% if random.discount_price %}
                                     <del class="mr-3">${{ random.discount_price }}</del>
                                {% endif %}
                                {% if random.is_free %}
                                    <span>Free</span>
                                {% else %}
                                     <span>${{ random.price }}</span>
                                {% endif %}</div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

</div>

<div class="py-5 block-22">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6 mb-4 mb-md-0 pr-md-5">
                <h2 class="heading">Create cool websites</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi accusantium optio und.</p>
            </div>
            <div class="col-md-6">
                <form action="#" class="subscribe">
                    <div class="form-group">
                        <input type="email" class="form-control email" placeholder="Enter email">
                        <input type="submit" class="btn btn-primary submit" value="Subscribe">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}