app/blog/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
router.register('post', views.PostViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('post-rud/<int:pk>/', views.BodyUpdateDelete.as_view()),
    path('<int:post_id>/comment-list-create/', views.CommentListCreateApiView.as_view())

]

app/blog/urls.py
from django.urls import path, include

app_name = 'blog'

urlpatterns = [
    path('v1/', include('app.blog.v1.urls')),

    # api
    path('api/', include('app.blog.api.urls')),
]

app/blog/v1/urls.py
from django.urls import path
from .views import Blog, BlogDetail#1 usul
from django.views.generic import TemplateView #2 usul


urlpatterns = [
    # path('blog/', blog, name='blog'),
    # path('detail-blog/<int:pk>/', detail, name='detail'),
    # path('blog/', TemplateView.as_view(template_name='blog/post_list.html'), name='blog'), #2 usul
    path('blog/', Blog.as_view(), name='blog'),
    path('detail/<int:pk>/', BlogDetail.as_view(), name='blog_detail'),
]

app/course/v1/urls.py
from django.urls import path
from .views import CourseView, CourseDetail, lesson_detail

urlpatterns = [
    path('course/', CourseView.as_view(), name='course'),
    path('detail/<int:pk>/', CourseDetail.as_view(), name='detail'),
    path('detail/<int:course_id>/lesson/<int:pk>/', lesson_detail, name='lesson_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import RedirectView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="EDU API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    # swagger
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('admin/', admin.site.urls),



#]
# urlpatterns += i18n_patterns(  # i18 ni urlpatternsga qoshsak barchasi tarjima qilinadi

    # local app
    path('', RedirectView.as_view(pattern_name='main:index')), #patern_name - bu v1/ ga birdaniga otvoradi kak indexga
    path('', include('app.main.urls', namespace='main')),
    path('account/', include('app.account.urls', namespace='account')),
    path('blog/', include('app.blog.urls', namespace='blog')),
    path('course/', include('app.course.urls', namespace='course'))

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/blog/models.py
from django.db import models
from django.db.models.signals import post_save
from app.main.models import Category, Tag
from django.conf import settings
from ckeditor.fields import RichTextField


class Post(models.Model):
    title = models.CharField(max_length=221)
    image = models.ImageField(upload_to='blog/')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    tags = models.ManyToManyField(Tag)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Body(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_body')
    body = RichTextField()
    is_script = models.BooleanField(default=False)


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    parent_comment = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='comments') # urldan oldik
    body = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    top_level_comment_id = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"comment of {self.author} ({self.id})"

    @property # property - bu htmlda chaqirvolish uchun yoziladi yani nuqta bn chaqirladi
    def get_related_comments(self):
        qs = Comment.objects.filter(top_level_comment_id=self.id).exclude(id=self.id)
        if qs:
            return qs
        return None


def comment_post_save(instance, sender, created, *args, **kwargs):
    if created:
        top_level_comment = instance
        while top_level_comment.parent_comment:
            top_level_comment = top_level_comment.parent_comment
        instance.top_level_comment_id = top_level_comment.id
        instance.save()


post_save.connect(comment_post_save, sender=Comment)

app/blog/api/views.py
from rest_framework import viewsets, status, permissions, generics
from rest_framework.response import Response
from .serializer import PostSerializer, PostDetailSerializer, BodySerializer, CommentSerializer
from ..models import Post, Body, Comment


class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()


    def get_serializer_class(self):
        if self.action in ['create', 'update', 'partial_update']: # partial_update - bu retrieve
            return PostSerializer # if list ichidagilar bolsa Postserializer ishlidi
        return PostDetailSerializer # aks holda put, patch, post ishlidi

class BodyUpdateDelete(generics.RetrieveUpdateDestroyAPIView):
    queryset = Body.objects.all()
    serializer_class = BodySerializer


class CommentListCreateApiView(generics.ListCreateAPIView):
    # http://127.0.0.0.8000/blog/api/{post_id}/comment-list-create/
    queryset = Comment.objects.filter(parent_comment__isnull=True) # commentni otasi bolish kerak emas
    serializer_class = CommentSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

    def get_serializer_context(self):
        ctx = super().get_serializer_context()
        ctx['post_id'] = self.kwargs.get('post_id')
        return ctx

    def get_queryset(self):
        qs = super().get_queryset()
        post_id = self.kwargs.get('post_id')
        qs = qs.filter(post_id=post_id)
        return qs

app/blog/v1/views.py
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.http import Http404
from django.db.models import Q
from django.shortcuts import render, redirect
from app.blog.models import Post, Comment, Body, Category, Tag
from app.course.models import Course


# def blog(request):
#     ctx = {
#
#     }
#     return render(request, "blog/post_list.html", ctx)
#
#
# def detail(request, pk):
#     ctx = {
#
#     }
#     return render(request, 'blog/blog-single.html', ctx)


class Blog(generic.ListView):
    # template_name = 'blog/post_list.html' #app_name/<model_name>_list.html
    queryset = Post.objects.all()
    paginate_by = 2
    ordering = ('-id',)

    def get_context_data(self, *, object_list=None, **kwargs):
        ctx = super().get_context_data()
        ctx['categories'] = Category.objects.all()
        ctx['tags'] = Tag.objects.all()
        ctx['recent_courses'] = Course.objects.order_by("-id")[:3]
        return ctx

    def get_queryset(self):  # moshlashuvchan filterlar
        qs = super().get_queryset()
        q = self.request.GET.get('q')
        cat = self.request.GET.get('category')
        tag = self.request.GET.get('tag')
        q_conditions = Q()
        if q:
            q_conditions = Q(title__icontains=q)
        cat_conditions = Q()
        if cat:
            cat_conditions = Q(category__title__exact=cat)
        tag_conditions = Q()
        if tag:
            tag_conditions = Q(tags__title__exact=tag)
        qs = qs.filter(q_conditions, cat_conditions, tag_conditions)
        return qs

    # def get(self, request, *args, **kwargs): #agar List db yozganda shuni ishlatamiz
    #     ctx = {
    #
    #     }
    #     return render(request, self.template_name, ctx)
    #
    # def post(self, request, *args, **kwargs):
    #     ctx = {
    #
    #     }
    #     return render(request, self.template_name, ctx)


class BlogDetail(generic.View):
    template_name = 'blog/blog-single.html'
    lookup_filed = 'pk'
    queryset = Post.objects.all()

    def get_object(self, pk):
        try:
            post = self.queryset.get(id=pk)
        except Post.DoesNotExist:
            raise Http404()  # raise = bu butun prayektni toxtatadi except ichiga qaytarib beradi
        return post

    def get_context_data(self, pk, *args, **kwargs):
        ctx = {
            'object': self.get_object(pk)
        }
        return ctx

    def get(self, request, pk):  # get - bu malumotni karob kada ochiqligica yetkazib beradi
        ctx = self.get_context_data(pk)
        comments = Comment.objects.filter(post_id=pk, parent_comment__isnull=True)
        ctx['comments'] = comments
        return render(request, self.template_name, ctx)

    def post(self, request, pk, *args, **kwargs): # post - bu malumotni karobkada yopiq holatda va hech kmga korinmidigan qilib yetkazib beradi
        ctx = self.get_context_data(pk)

        if not request.user.is_authenticated:
            return redirect('account:login')

        comment_id = request.GET.get('comment_id', None)
        user_id = request.user.id
        body = request.POST.get('body')
        if body:
            obj = Comment.objects.create(author_id=user_id, post_id=pk, body=body, parent_comment_id=comment_id)
            return redirect(reverse('blog:blog_detail', kwargs={'pk': pk}) + f"#comments_{obj.id}")  # agar kwarglar bolsa reverse_lazy ishlatamiz
        return render(request, self.template_name, ctx)

templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="site-hero site-sm-hero overlay" data-stellar-background-ratio="0.5"
         style="background-image: url({{ object.image.url }});">
    <div class="container">
        <div class="row align-items-center justify-content-center site-hero-sm-inner">
            <div class="col-md-12 text-center">
                <div class="mb-5 element-animate">
                    <h1 class="mb-2">{{ object.title }}</h1>
                    <p class="bcrumb">by <a href="#">{{ object.author }}</a> on <a href="#">{{ object.created_date|date }}</a></p>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="site-section bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-8 order-md-2 pl-lg-5">
                <div class="row">
                    <div class="col-md-12 col-lg-12 mb-5">
                        {% for body in object.body_set.all %}
                            {% if body.is_script %}
                            <blockquote>
                                <p>{{ body.body|safe }}</p>
                            </blockquote>
                            {% else %}
                                <p class="">{{ body.body|safe }}</p>
                            {% endif %}
                        {% endfor %}
                        <div class="pt-5">
                            <p>Categories:
                                <a href="{% url 'blog:blog' %}?category{{ object.category.title }}">{{ object.category.title }} </a>
                                Tags:
                                {% for tag in object.tags.all %}
                                    <a href="{% url 'blog:blog' %}?tag{{ tag.title}}">#{{ tag.title }}</a>
                                {% endfor %}
                            </p>
                        </div>
                        <div class="pt-5">
                            <h3 class="mb-5">{{ object.comment_set.count}} Comments</h3>
                            <ul class="comment-list">
                             {% for comment in comments %}
                                <li class="comment" id="comment_{{ comment.id }}">
                                    <div class="vcard bio">
                                        {% if comment.author.image %}
                                            <img src="{{ comment.author.image.url }}" alt="Image placeholder">
                                        {% else %}
                                            <img src="{% static 'images/anonymous .png' %}" alt="Image placeholder">
                                        {% endif %}
                                    </div>
                                    <div class="comment-body">
                                        <h3>{{ comment.author }}</h3>
                                        <div class="meta">{{ comment.created_date }}</div>
                                        <p>{{ comment.body }}</p>
                                        <p><a href="{{ request.get_path }}?comment_id={{ comment.id }}#message" class="reply">Reply</a></p>
                                    </div>
                                        {% if comment.get_related_comments %}
                                        <ul class="children">
                                         {% for children_comment in comment.get_related_comments %}
                                        <li class="comment" id="comment_{{ child_comment.id }}">
                                            <div class="vcard bio">
                                                {% if children_comment.author.image %}
                                                    <img src="{{ children_comment.author.image.url }}" alt="Image placeholder">
                                                {% else %}
                                                    <img src="{% static 'images/anonymous .png' %}" alt="Image placeholder">
                                                {% endif %}
                                            </div>
                                            <div class="comment-body">
                                                <h3>{{ children_comment.author }}</h3>
                                                <div class="meta">{{ children_comment.created_date }}</div>
                                                <p><code>@{{ children_comment.parent_comment.author }}</code> {{ children_comment.body }}</p>
                                                <p><a href="{{ request.get_path }}?comment_id={{ children_comment.id }}#message" class="reply">Reply</a></p>
                                            </div>
                                        </li>
                                         {% endfor %}
                                    </ul>
                                    {% endif %}
                                </li>
                             {% endfor %}
                            </ul>

                            <div class="comment-form-wrap pt-5">
                                <h3 class="mb-5">Leave a comment</h3>
                                <form method="post" class="bg-light">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="message">Message</label>
                                        <textarea name="body" id="message" cols="30" rows="10"
                                                  class="form-control"></textarea>
                                    </div>
                                    <div class="form-group">
                                        <input type="submit" value="Post Comment" class="btn btn-primary">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-lg-4 order-md-1">
                <div class="block-24 mb-5">
                    <h3 class="heading">Categories</h3>
                    <ul>
                        <li><a href="#">Laravel <span>10</span></a></li>
                        <li><a href="#">PHP <span>43</span></a></li>
                        <li><a href="#">JavaScript <span>21</span></a></li>
                        <li><a href="#">Python <span>65</span></a></li>
                        <li><a href="#">iOS <span>34</span></a></li>
                        <li><a href="#">Android <span>45</span></a></li>
                        <li><a href="#">Swift <span>22</span></a></li>
                    </ul>
                </div>
                <div class="block-25 mb-5">
                    <div class="heading">Recent Courses</div>
                    <ul>
                        <li>
                            <a href="#" class="d-flex">
                                <figure class="image mr-3">
                                    <img src="{% static 'images/img_2_b.jpg' %}" alt="" class="img-fluid">
                                </figure>
                                <div class="text">
                                    <h3 class="heading">Create cool websites using this template</h3>
                                    <span class="meta">$34</span>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="d-flex">
                                <figure class="image mr-3">
                                    <img src="{% static 'images/img_2_b.jpg' %}" alt="" class="img-fluid">
                                </figure>
                                <div class="text">
                                    <h3 class="heading">Create cool websites using this template</h3>
                                    <span class="meta">$34</span>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="d-flex">
                                <figure class="image mr-3">
                                    <img src="{% static 'images/img_2_b.jpg' %}" alt="" class="img-fluid">
                                </figure>
                                <div class="text">
                                    <h3 class="heading">Create cool websites using this template</h3>
                                    <span class="meta">$34</span>
                                </div>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="block-26">
                    <h3 class="heading">Tags</h3>
                    <ul>
                        <li><a href="#">code</a></li>
                        <li><a href="#">design</a></li>
                        <li><a href="#">typography</a></li>
                        <li><a href="#">development</a></li>
                        <li><a href="#">creative</a></li>
                        <li><a href="#">codehack</a></li>
                    </ul>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="py-5 block-22">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6 mb-4 mb-md-0 pr-md-5">
                <h2 class="heading">Create cool websites</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi accusantium optio und.</p>
            </div>
            <div class="col-md-6">
                <form action="#" class="subscribe">
                    <div class="form-group">
                        <input type="email" class="form-control email" placeholder="Enter email">
                        <input type="submit" class="btn btn-primary submit" value="Subscribe">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="site-hero site-sm-hero overlay" data-stellar-background-ratio="0.5"
         style="background-image: url({% static 'images/big_image_2.jpg' %});">
    <div class="container">
        <div class="row align-items-center justify-content-center site-hero-sm-inner">
            <div class="col-md-7 text-center">
                <div class="mb-5 element-animate">
                    <h1 class="mb-2">Our Blog</h1>
                    <p class="bcrumb"><a href="{% url 'main:index' %}">Home</a> <span
                            class="sep ion-android-arrow-dropright px-2"></span> <span class="current">Blog</span></p>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="site-section bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-8 order-md-2">
                <div class="row">
                   {% for post in object_list %} {#agar hech narsa contextga yzomasa  default qiymati object_list bolib keladi #}
                    <div class="col-md-12 col-lg-6 mb-5">
                        <div class="block-20 ">
                            <figure>
                                <a href="{% url 'blog:blog_detail' post.id %}"><img src="{{ post.image.url }}" alt="" class="img-fluid"></a>
                            </figure>
                            <div class="text">
                                <h3 class="heading"><a href="{% url 'blog:blog_detail' post.id %}">{{ post.title }}</a></h3>
                                <div class="meta">
                                    <div><a href="{% url 'blog:blog_detail' post.id %}"><span class="ion-android-calendar"></span> {{ post.created_date|date }}</a></div>
                                    <div><a href="{% url 'blog:blog_detail' post.id %}"><span class="ion-android-person"></span> {{ post.author }}</a></div>
                                    <div><a href="{% url 'blog:blog_detail' post.id %}"><span class="ion-chatbubble"></span> {{ post.comment_set.count }}</a></div>
                                 </div>
                                </div>
                            </div>
                        </div>
                     {% endfor %}
                </div>

                <div class="row mb-5">
                    <div class="col-md-12 text-center">
                        <div class="block-27">
                            {% if is_paginated %}
                            <ul>
                                {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
                                {% endif %}
                            {% for page in paginator.page_range %}
                                {% if page_obj.number == page %}
                                <li class="active"><span>{{ page }}</span></li>
                                {% else %}
                                <li><a href="?page={{ page }}">{{ page }}</a></li>
                                {% endif %}
                            {% endfor %}
                                {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
                                {% endif %}
                            </ul>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-lg-4 order-md-1">
                <div class="block-24 mb-5">
                    <h3 class="heading">Categories</h3>
                    <ul>
                        {% for category in categories %}
                            <li><a href="{% if request.GET %}{{ request.get_full_path }}&category={{ category.title }}{% else %}{{ request.get_full_path }}?category={{ category.title }}{% endif %}">{{ category.title }} <span>{{ category.post_set.count }}</span></a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="block-25 mb-5">
                    <div class="heading">Recent Courses</div>
                    <ul>
                        {% for recent in recent_courses %}
                            <li>
                            <a href="{% url 'course:detail' recent.id %}" class="d-flex">
                                <figure class="image mr-3">
                                    <img src="{{ recent.cover.url }}" alt="" class="img-fluid">
                                </figure>
                                <div class="text">
                                    <h3 class="heading">{{ recent.title }}</h3>
                                    <span class="meta">
                                        {% if discount_price %}
                                            <del class="mr-3">${{ recent.discount_price }}</del>
                                        {% endif %}
                                        {% if recent.price %}
                                            <span>${{ recent.price }}</span>
                                        {% else %}
                                            <span>Free</span>
                                        {% endif %}
                                    </span>
                                </div>
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="block-26">
                    <h3 class="heading">Tags</h3>
                    <ul>
                        {% for tag in tags %}
                            <li><a href="{% if request.GET %}{{ request.get_full_path }}&tag={{ tag.title }}{% else %}{{ request.get_full_path }}?tag={{ tag.title }}{% endif %}">{{ tag.title }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="py-5 block-22">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6 mb-4 mb-md-0 pr-md-5">
                <h2 class="heading">Create cool websites</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi accusantium optio und.</p>
            </div>
            <div class="col-md-6">
                <form action="#" class="subscribe">
                    <div class="form-group">
                        <input type="email" class="form-control email" placeholder="Enter email">
                        <input type="submit" class="btn btn-primary submit" value="Subscribe">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}