app/account/v1/urls.py
from django.urls import path, reverse, reverse_lazy
from django.contrib.auth.views import LoginView, \
    PasswordChangeView, PasswordChangeDoneView, LogoutView, \
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .views import RegisterView, logout_view, profile_info, profile_update, my_course
# from .views import login_view, register_view


urlpatterns = [
    # path('login/', login_view, name='login'),
    # path('register/', register_view, name='register')

    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', logout_view, name='logout'),

    path('profile_info/', profile_info, name='info'),
    path('profile_update/<int:pk>/', profile_update, name='update'),
    path('my_courses/', my_course, name='mycourses'),

    #changepassword
    path('password_change/',
         PasswordChangeView.as_view(template_name='account/change_password/change_password_form.html',
                                    success_url=reverse_lazy('account:change_done')),
         name='change_password'),
    path('password_change/done/',
         PasswordChangeDoneView.as_view(template_name='account/change_password/password_change_done.html'),
         name='change_done'),

    #passwordreset email jonatish
    path('password_reset/send/',
         PasswordResetView.as_view(
             template_name='account/reset_password/password_reset_form.html',
             email_template_name='account/reset_password/password_reset_email.html',  #bu emailga boradigan habar
             success_url=reverse_lazy('account:password_done')),
         name='password_reset',),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(template_name='account/reset_password/password_reset_done.html'),
         name='password_done'),
    path('password_reset/confirm/<str:uidb64>/<str:token>/',
         PasswordResetConfirmView.as_view(
             template_name='account/reset_password/password_reset_confirm.html',
             success_url=reverse_lazy("account:password_complete")),
         name='password_confirm', ),
    path('password_reset/complete/',
         PasswordResetCompleteView.as_view(template_name='account/reset_password/password_reset_complete.html'),
         name='password_complete')
]

app/blog/urls.py
from django.urls import path, include

app_name = 'blog'

urlpatterns = [
    path('v1/', include('app.blog.v1.urls')),

    # api
    path('api/', include('app.blog.api.urls')),
]

app/course/urls.py
from django.urls import path, include

app_name = 'course'

urlpatterns = [
    path('v1/', include('app.course.v1.urls')),
    path('api/', include('app.course.api.urls')),

]

app/main/v1/urls.py
from django.urls import path
from .views import index, contact, about

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import RedirectView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="EDU API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    # swagger
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('admin/', admin.site.urls),



#]
# urlpatterns += i18n_patterns(  # i18 ni urlpatternsga qoshsak barchasi tarjima qilinadi

    # local app
    path('', RedirectView.as_view(pattern_name='main:index')), #patern_name - bu v1/ ga birdaniga otvoradi kak indexga
    path('', include('app.main.urls', namespace='main')),
    path('account/', include('app.account.urls', namespace='account')),
    path('blog/', include('app.blog.urls', namespace='blog')),
    path('course/', include('app.course.urls', namespace='course'))

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<!-- Mirrored from preview.colorlib.com/theme/university/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 25 Feb 2023 09:02:44 GMT -->
<head>
    <title>Free Education Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block style %}

    {% endblock %}
    <script nonce="d2bedb71-7ed5-4286-ba75-1544d00b0e31">
        (function(w,d){!function(bw,bx,by,bz){bw[by]=bw[by]||{};bw[by].executed=[];bw.zaraz={deferred:[],listeners:[]};bw.zaraz.q=[];bw.zaraz._f=function(bA){return function(){var bB=Array.prototype.slice.call(arguments);bw.zaraz.q.push({m:bA,a:bB})}};for(const bC of["track","set","debug"])bw.zaraz[bC]=bw.zaraz._f(bC);bw.zaraz.init=()=>{var bD=bx.getElementsByTagName(bz)[0],bE=bx.createElement(bz),bF=bx.getElementsByTagName("title")[0];bF&&(bw[by].t=bx.getElementsByTagName("title")[0].text);bw[by].x=Math.random();bw[by].w=bw.screen.width;bw[by].h=bw.screen.height;bw[by].j=bw.innerHeight;bw[by].e=bw.innerWidth;bw[by].l=bw.location.href;bw[by].r=bx.referrer;bw[by].k=bw.screen.colorDepth;bw[by].n=bx.characterSet;bw[by].o=(new Date).getTimezoneOffset();if(bw.dataLayer)for(const bJ of Object.entries(Object.entries(dataLayer).reduce(((bK,bL)=>({...bK[1],...bL[1]})))))zaraz.set(bJ[0],bJ[1],{scope:"page"});bw[by].q=[];for(;bw.zaraz.q.length;){const bM=bw.zaraz.q.shift();bw[by].q.push(bM)}bE.defer=!0;for(const bN of[localStorage,sessionStorage])Object.keys(bN||{}).filter((bP=>bP.startsWith("_zaraz_"))).forEach((bO=>{try{bw[by]["z_"+bO.slice(7)]=JSON.parse(bN.getItem(bO))}catch{bw[by]["z_"+bO.slice(7)]=bN.getItem(bO)}}));bE.referrerPolicy="origin";bE.src="../../cdn-cgi/zaraz/sd0d9.js?z="+btoa(encodeURIComponent(JSON.stringify(bw[by])));bD.parentNode.insertBefore(bE,bD)};["complete","interactive"].includes(bx.readyState)?zaraz.init():bw.addEventListener("DOMContentLoaded",zaraz.init)}(w,d,"zarazData","script");})(window,document);
    </script>
</head>
<body>

{% include 'navbar.html' %}

{% block content %}



{% endblock %}

{% include 'footer.html' %}

{% include 'loader.html' %}


<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.0.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

{% block script %}


{% endblock %}


<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');

</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993"
        integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA=="
        data-cf-beacon='{"rayId":"79ef3fd29a92d987","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2023.2.0","si":100}'
        crossorigin="anonymous"></script>
</body>

<!-- Mirrored from preview.colorlib.com/theme/university/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 25 Feb 2023 09:02:54 GMT -->
</html>

templates/footer.html
<footer class="site-footer">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-6 col-lg-3 mb-5 mb-lg-0">
                <h3>University</h3>
                <p>Perferendis eum illum voluptatibus dolore tempora consequatur minus asperiores temporibus.</p>
            </div>
            <div class="col-md-6 col-lg-3 mb-5 mb-lg-0">
                <h3 class="heading">Quick Link</h3>
                <div class="row">
                    <div class="col-md-6">
                        <ul class="list-unstyled">
                            <li><a href="#">Home</a></li>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Courses</a></li>
                            <li><a href="#">Pages</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <ul class="list-unstyled">
                            <li><a href="#">News</a></li>
                            <li><a href="#">Support</a></li>
                            <li><a href="#">Contact</a></li>
                            <li><a href="#">Privacy</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3 mb-5 mb-lg-0">
                <h3 class="heading">Blog</h3>
                <div class="block-21 d-flex mb-4">
                    <div class="text">
                        <h3 class="heading mb-0"><a href="#">Consectetur Adipisicing Elit</a></h3>
                        <div class="meta">
                            <div><a href="#"><span class="ion-android-calendar"></span> May 29, 2018</a></div>
                            <div><a href="#"><span class="ion-android-person"></span> Admin</a></div>
                            <div><a href="#"><span class="ion-chatbubble"></span> 19</a></div>
                        </div>
                    </div>
                </div>
                <div class="block-21 d-flex mb-4">
                    <div class="text">
                        <h3 class="heading mb-0"><a href="#">Dolore Tempora Consequatur</a></h3>
                        <div class="meta">
                            <div><a href="#"><span class="ion-android-calendar"></span> May 29, 2018</a></div>
                            <div><a href="#"><span class="ion-android-person"></span> Admin</a></div>
                            <div><a href="#"><span class="ion-chatbubble"></span> 19</a></div>
                        </div>
                    </div>
                </div>
                <div class="block-21 d-flex mb-4">
                    <div class="text">
                        <h3 class="heading mb-0"><a href="#">Perferendis eum illum</a></h3>
                        <div class="meta">
                            <div><a href="#"><span class="ion-android-calendar"></span> May 29, 2018</a></div>
                            <div><a href="#"><span class="ion-android-person"></span> Admin</a></div>
                            <div><a href="#"><span class="ion-chatbubble"></span> 19</a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3 mb-5 mb-lg-0">
                <h3 class="heading">Contact Information</h3>
                <div class="block-23">
                    <ul>
                        <li><span class="icon ion-android-pin"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                        </li>
                        <li><a href="#"><span class="icon ion-ios-telephone"></span><span
                                class="text">+2 392 3929 210</span></a></li>
                        <li><a href="#"><span class="icon ion-android-mail"></span><span class="text"><span
                                class="__cf_email__" data-cfemail="630a0d050c231a0c1611070c0e020a0d4d000c0e">[email&#160;protected]</span></span></a>
                        </li>
                        <li><span class="icon ion-android-time"></span><span class="text">Monday &mdash; Friday 8:00am - 5:00pm</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row pt-5">
            <div class="col-md-12 text-center copyright">
                <p class="float-md-left">
                    Copyright &copy;<script data-cfasync="false"
                                            src="../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
                    <script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by
                    <a href="https://colorlib.com/" target="_blank" class="text-primary">Colorlib</a>
                </p>
                <p class="float-md-right">
                    <a href="#" class="fa fa-facebook p-2"></a>
                    <a href="#" class="fa fa-twitter p-2"></a>
                    <a href="#" class="fa fa-linkedin p-2"></a>
                    <a href="#" class="fa fa-instagram p-2"></a>
                </p>
            </div>
        </div>
    </div>
</footer>

templates/loader.html
<div id="loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#f4b214"/>
    </svg>
</div>

templates/navbar.html
{% load i18n %}
{% get_current_language as CURRENT_LANGUAGE %}
{% get_available_languages as AVAILABLE_LANGUAGES %}
{% get_language_info_list for AVAILABLE_LANGUAGES as languages %}

<header role="banner">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand absolute" href="{% url 'main:index' %}">University</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05"
                    aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse navbar-light" id="navbarsExample05">
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'main:index' %}">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="{% url 'course:course' %}">Courses</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:blog' %}">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:contact' %}">Contact</a>
                    </li>
                </ul>
                <ul class="navbar-nav absolute-right">
                    <li>
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'account:info' %}"> {{ request.user.username }}</a> <a href="{% url 'account:logout' %}">Logout</a>
                        {% else %}
                            <a href="{% url 'account:login' %}">Login</a> / <a href="{% url 'account:register' %}">Register</a>
                        {% endif %}
                    </li>

<!--                    {% for language in languages %}-->
<!--                    <li class="nav-item">-->
<!--                        <a class="nav-link" href="/{{ language.code }}/">{{ language.name }} /</a>-->
<!--                    </li>-->
<!--                    {% endfor %}-->
                </ul>
            </div>
        </div>
    </nav>
</header>